spring:
  datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver

hello-world: jack7
